services:
  web:
    build:
      context: .
    container_name: goldenzona_backend
    env_file:
      - .env
    command: >
      sh -c "
        uv run manage.py makemigrations &&
        uv run manage.py migrate &&
        uv run manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - .:/app
      - venv:/app/.venv
    ports:
      - "8001:8001"
    restart: unless-stopped

    
volumes:
  venv: